/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundryskuy;

/**
 *
 * @author Acer
 */
public class HalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Isi = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));
        PanelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(200, 162, 122));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gidolinya", 0, 18)); // NOI18N
        jLabel2.setText("LAUNDRYSKUY");
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Icon/Logo.png"))); // NOI18N
        Header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 40, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Icon/Menu.png"))); // NOI18N
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, -1, 50));

        PanelUtama.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 70));

        Isi.setBackground(new java.awt.Color(255, 255, 255));
        Isi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Background.jpg"))); // NOI18N
        Isi.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-510, 60, 1000, 300));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Background.jpg"))); // NOI18N
        Isi.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 680, 380));

        jLabel6.setFont(new java.awt.Font("Gidolinya", 0, 24)); // NOI18N
        jLabel6.setText("INFO");
        Isi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 60, 30));

        jLabel7.setFont(new java.awt.Font("Gidolinya", 0, 18)); // NOI18N
        jLabel7.setText("Adalah laundry dengan pelayanan yang santuy, cepat,");
        Isi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 570, 30));

        jLabel8.setFont(new java.awt.Font("Gidolinya", 0, 18)); // NOI18N
        jLabel8.setText("terbaik yang ada di negeri ini kami jamin anda puas :)");
        Isi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, 30));

        jLabel10.setFont(new java.awt.Font("Gidolinya", 0, 24)); // NOI18N
        jLabel10.setText("LAUNDRY SKUY");
        Isi.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 150, 30));

        jLabel11.setFont(new java.awt.Font("Gidolinya", 0, 18)); // NOI18N
        jLabel11.setText("rapih, dan nyaman. Dengan menggunakan mesin cuci");
        Isi.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, 30));

        jLabel12.setFont(new java.awt.Font("Gidolinya", 0, 18)); // NOI18N
        jLabel12.setText("Alamat : Jln Intisari No 13");
        Isi.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, 40));

        jLabel13.setFont(new java.awt.Font("Gidolinya", 0, 18)); // NOI18N
        jLabel13.setText("Telepon : 091169212");
        Isi.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, 40));

        PanelUtama.add(Isi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1080, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Isi;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
