package edu.laundryskuy.view;

import edu.laundryskuy.controller.PelangganController;
import edu.laundryskuy.database.LaundryskuyDatabase;
import edu.laundryskuy.entity.Pelanggan;
import edu.laundryskuy.error.PelangganException;
import edu.laundryskuy.event.PelangganListener;
import edu.laundryskuy.model.PelangganModel;
import edu.laundryskuy.model.TablePelangganModel;
import edu.laundryskuy.service.PelangganDao;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class HalamanUtama extends javax.swing.JPanel implements PelangganListener, ListSelectionListener{

    private TablePelangganModel tableModel;
    private PelangganModel model;
    private PelangganController controller;
    
    public HalamanUtama() {
        tableModel = new TablePelangganModel();
        
        model = new PelangganModel();
        model.setListener(this);
        
        controller = new PelangganController();
        controller.setModel(model);
        
        initComponents();
        
        tablePelanggan.getSelectionModel().addListSelectionListener(this);
        tablePelanggan.setModel(tableModel);
    }

    public JTable getTablePelanggan() {
        return tablePelanggan;
    }

    public JTextField getTxtBerat() {
        return txtBerat;
    }

    public JTextField getTxtNama() {
        return txtNama;
    }

    public JTextField getTxtNo() {
        return txtNo;
    }

    public JTextField getTxtSelesai() {
        return txtSelesai;
    }

    public JTextField getTxtTelp() {
        return txtTelp;
    }

    public JTextField getTxtTerima() {
        return txtTerima;
    }

    public JTextField getTxtTotal() {
        return txtTotal;
    }

    public JTextField getTxtKetLunas() {
        return txtKetLunas;
    }

    public JTextField getTxtKetSelesai() {
        return txtKetSelesai;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        TextHeader = new javax.swing.JLabel();
        IconHeader = new javax.swing.JLabel();
        btnMenu = new javax.swing.JPanel();
        IconMenu = new javax.swing.JLabel();
        Isi = new javax.swing.JPanel();
        Beranda = new javax.swing.JPanel();
        TextBeranda1 = new javax.swing.JLabel();
        TextBeranda2 = new javax.swing.JLabel();
        TextBeranda3 = new javax.swing.JLabel();
        TextBeranda4 = new javax.swing.JLabel();
        TextBeranda5 = new javax.swing.JLabel();
        TextBeranda6 = new javax.swing.JLabel();
        TextBeranda7 = new javax.swing.JLabel();
        ImageBeranda1 = new javax.swing.JLabel();
        ImageBeranda2 = new javax.swing.JLabel();
        ImageBeranda3 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnKasir = new javax.swing.JPanel();
        TextMenuKasir = new javax.swing.JLabel();
        btnData = new javax.swing.JPanel();
        TextMenuData = new javax.swing.JLabel();
        TextMenu = new javax.swing.JLabel();
        Kasir = new javax.swing.JPanel();
        TextKasir = new javax.swing.JLabel();
        TextKasirNo = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        TextKasirNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        TextKasirBerat = new javax.swing.JLabel();
        txtBerat = new javax.swing.JTextField();
        TextKasirTerima = new javax.swing.JLabel();
        txtTerima = new javax.swing.JTextField();
        TextKasirSelesai = new javax.swing.JLabel();
        txtSelesai = new javax.swing.JTextField();
        TextKasirTelp = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        btnHitung = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JPanel();
        TextKasirSimpan = new javax.swing.JLabel();
        btnReset = new javax.swing.JPanel();
        TextKasirReset = new javax.swing.JLabel();
        TextKasirTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        TextKasirKet = new javax.swing.JLabel();
        txtKetSelesai = new javax.swing.JTextField();
        ImageKasir1 = new javax.swing.JLabel();
        ImageKasir2 = new javax.swing.JLabel();
        ImageKasir3 = new javax.swing.JLabel();
        btnKasirKeluar = new javax.swing.JPanel();
        TextKasirKeluar = new javax.swing.JLabel();
        btnLihatData = new javax.swing.JPanel();
        TextLihatData = new javax.swing.JLabel();
        btnKasirKembali = new javax.swing.JPanel();
        TextKasirKembali = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextKasirKet1 = new javax.swing.JLabel();
        TextKasirKet2 = new javax.swing.JLabel();
        txtKetLunas = new javax.swing.JTextField();
        Data = new javax.swing.JPanel();
        TextData = new javax.swing.JLabel();
        ImageData1 = new javax.swing.JLabel();
        ImageData2 = new javax.swing.JLabel();
        ImageData3 = new javax.swing.JLabel();
        btnDataHapus = new javax.swing.JPanel();
        TextKembali1 = new javax.swing.JLabel();
        btnDataUbah = new javax.swing.JPanel();
        TextKembali5 = new javax.swing.JLabel();
        btnDataKembali1 = new javax.swing.JPanel();
        TextKembali3 = new javax.swing.JLabel();
        btnDataKembali2 = new javax.swing.JPanel();
        TextKembali2 = new javax.swing.JLabel();
        btnDataKeluar = new javax.swing.JPanel();
        TextDataKeluar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePelanggan = new javax.swing.JTable();
        TextKembali4 = new javax.swing.JLabel();

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));
        PanelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(87, 138, 175));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextHeader.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        TextHeader.setText("LAUNDRYSKUY");
        Header.add(TextHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        IconHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Icon/Logo.png"))); // NOI18N
        Header.add(IconHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, 50));

        btnMenu.setBackground(new java.awt.Color(87, 138, 175));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });
        btnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Icon/Menu.png"))); // NOI18N
        btnMenu.add(IconMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        Header.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 20, 50, 30));

        PanelUtama.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 70));

        Isi.setBackground(new java.awt.Color(255, 255, 255));
        Isi.setLayout(new java.awt.CardLayout());

        Beranda.setBackground(new java.awt.Color(255, 255, 255));
        Beranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextBeranda1.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        TextBeranda1.setText("S E L A M A T  D A T A N G");
        Beranda.add(TextBeranda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 30));

        TextBeranda2.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextBeranda2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextBeranda2.setText("Semoga anda puas dengan pelayanan kami :)");
        Beranda.add(TextBeranda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 490, 40));

        TextBeranda3.setFont(new java.awt.Font("Leelawadee", 2, 24)); // NOI18N
        TextBeranda3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBeranda3.setText("LaundrySkuy");
        Beranda.add(TextBeranda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 150, 30));

        TextBeranda4.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextBeranda4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBeranda4.setText("Adalah laundry dengan pelayanan yang santuy,");
        Beranda.add(TextBeranda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 590, 30));

        TextBeranda5.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextBeranda5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBeranda5.setText("cepat, rapih, dan nyaman. Dengan menggunakan mesin cuci terbaik");
        Beranda.add(TextBeranda5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 730, 40));

        TextBeranda6.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextBeranda6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextBeranda6.setText("yang ada di negeri ini, kami juga menggunakan sabun dan pewangi ");
        Beranda.add(TextBeranda6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 760, 40));

        TextBeranda7.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextBeranda7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextBeranda7.setText("setara parfum dunia dengan bau yang tahan lama. ");
        Beranda.add(TextBeranda7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 760, 40));

        ImageBeranda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Beranda3.jpg"))); // NOI18N
        Beranda.add(ImageBeranda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, 450, -1));

        ImageBeranda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Beranda1.jpg"))); // NOI18N
        Beranda.add(ImageBeranda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 80, -1, -1));

        ImageBeranda3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Beranda2.jpg"))); // NOI18N
        Beranda.add(ImageBeranda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        Isi.add(Beranda, "card2");

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKasirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKasirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKasirMousePressed(evt);
            }
        });

        TextMenuKasir.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextMenuKasir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextMenuKasir.setText("K A S I R");

        javax.swing.GroupLayout btnKasirLayout = new javax.swing.GroupLayout(btnKasir);
        btnKasir.setLayout(btnKasirLayout);
        btnKasirLayout.setHorizontalGroup(
            btnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextMenuKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        btnKasirLayout.setVerticalGroup(
            btnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextMenuKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        Menu.add(btnKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        btnData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDataMousePressed(evt);
            }
        });

        TextMenuData.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextMenuData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextMenuData.setText("D A T A  P E L A N G G A N");

        javax.swing.GroupLayout btnDataLayout = new javax.swing.GroupLayout(btnData);
        btnData.setLayout(btnDataLayout);
        btnDataLayout.setHorizontalGroup(
            btnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextMenuData, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        btnDataLayout.setVerticalGroup(
            btnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextMenuData, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );

        Menu.add(btnData, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 360, -1));

        TextMenu.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        TextMenu.setText("M E N U");
        Menu.add(TextMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, -1));

        Isi.add(Menu, "card3");

        Kasir.setBackground(new java.awt.Color(255, 255, 255));
        Kasir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKasir.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        TextKasir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasir.setText("K A S I R");
        Kasir.add(TextKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 61, 298, -1));

        TextKasirNo.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirNo.setText("N O  R A K");
        Kasir.add(TextKasirNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 338, 35));

        txtNo.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        txtNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoActionPerformed(evt);
            }
        });
        Kasir.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 240, 35));

        TextKasirNama.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirNama.setText("N A M A  P E L A N G G A N");
        Kasir.add(TextKasirNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 338, 35));

        txtNama.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        txtNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        Kasir.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 240, 35));

        TextKasirBerat.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirBerat.setText("B E R A T  P A K A I A N (KG)");
        Kasir.add(TextKasirBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 323, 30));

        txtBerat.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        txtBerat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBerat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBeratActionPerformed(evt);
            }
        });
        txtBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBeratKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBeratKeyTyped(evt);
            }
        });
        Kasir.add(txtBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 70, 35));

        TextKasirTerima.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirTerima.setText("T A N G G A L   T E R I M A");
        Kasir.add(TextKasirTerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 323, 35));

        txtTerima.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        txtTerima.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTerima.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerimaActionPerformed(evt);
            }
        });
        Kasir.add(txtTerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 240, 35));

        TextKasirSelesai.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirSelesai.setText("T A N G G A L   S E L E S A I ");
        Kasir.add(TextKasirSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 338, 35));

        txtSelesai.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        txtSelesai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSelesai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelesaiActionPerformed(evt);
            }
        });
        Kasir.add(txtSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 240, 35));

        TextKasirTelp.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirTelp.setText("N O  T E L E P O N");
        Kasir.add(TextKasirTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 323, 30));

        txtTelp.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        txtTelp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTelp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });
        Kasir.add(txtTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 240, 35));

        btnHitung.setBackground(new java.awt.Color(87, 138, 175));
        btnHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHitungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHitungMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHitungMousePressed(evt);
            }
        });
        btnHitung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("H I T U N G");
        btnHitung.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        Kasir.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 200, 40));

        btnSimpan.setBackground(new java.awt.Color(87, 138, 175));
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSimpanMousePressed(evt);
            }
        });
        btnSimpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKasirSimpan.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKasirSimpan.setForeground(new java.awt.Color(255, 255, 255));
        TextKasirSimpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasirSimpan.setText("S I M P A N");
        btnSimpan.add(TextKasirSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 40));

        Kasir.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 750, 260, 40));

        btnReset.setBackground(new java.awt.Color(87, 138, 175));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnResetMousePressed(evt);
            }
        });
        btnReset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKasirReset.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKasirReset.setForeground(new java.awt.Color(255, 255, 255));
        TextKasirReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasirReset.setText("R E S E T");
        btnReset.add(TextKasirReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        Kasir.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, -1, 40));

        TextKasirTotal.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasirTotal.setText("T O T A L  P E M B A Y A R A N");
        Kasir.add(TextKasirTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 338, -1));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTotalKeyTyped(evt);
            }
        });
        Kasir.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 250, 35));

        TextKasirKet.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKasirKet.setText("P R O S E S / S E L E S A I");
        Kasir.add(TextKasirKet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 690, 270, 40));

        txtKetSelesai.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        txtKetSelesai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKetSelesai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtKetSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetSelesaiActionPerformed(evt);
            }
        });
        Kasir.add(txtKetSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 690, 220, 35));

        ImageKasir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Kasir2.jpg"))); // NOI18N
        Kasir.add(ImageKasir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 90, -1, -1));

        ImageKasir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Kasir5.jpg"))); // NOI18N
        Kasir.add(ImageKasir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 50, -1, -1));

        ImageKasir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Kasir1.jpg"))); // NOI18N
        Kasir.add(ImageKasir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, -1, -1));

        btnKasirKeluar.setBackground(new java.awt.Color(87, 138, 175));
        btnKasirKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKasirKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKasirKeluarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKasirKeluarMousePressed(evt);
            }
        });
        btnKasirKeluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKasirKeluar.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKasirKeluar.setForeground(new java.awt.Color(255, 255, 255));
        TextKasirKeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasirKeluar.setText("K E L U A R");
        btnKasirKeluar.add(TextKasirKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 40));

        Kasir.add(btnKasirKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 790, 320, 40));

        btnLihatData.setBackground(new java.awt.Color(87, 138, 175));
        btnLihatData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLihatDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLihatDataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLihatDataMousePressed(evt);
            }
        });
        btnLihatData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextLihatData.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextLihatData.setForeground(new java.awt.Color(255, 255, 255));
        TextLihatData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextLihatData.setText("L I H A T  D A T A");
        btnLihatData.add(TextLihatData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 40));

        Kasir.add(btnLihatData, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 670, 320, 40));

        btnKasirKembali.setBackground(new java.awt.Color(87, 138, 175));
        btnKasirKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKasirKembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKasirKembaliMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKasirKembaliMousePressed(evt);
            }
        });
        btnKasirKembali.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKasirKembali.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKasirKembali.setForeground(new java.awt.Color(255, 255, 255));
        TextKasirKembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasirKembali.setText("K E M B A L I  K E  B E R A N D A");
        btnKasirKembali.add(TextKasirKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 40));

        Kasir.add(btnKasirKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 730, 320, 40));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel2.setText("HARGA PER KILOGRAM");
        Kasir.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel3.setText("5000");
        Kasir.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));

        TextKasirKet1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKasirKet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasirKet1.setText("K E T E R A N G A N");
        Kasir.add(TextKasirKet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, 220, -1));

        TextKasirKet2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKasirKet2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasirKet2.setText("L U N A S / B E L U M  L U N A S");
        Kasir.add(TextKasirKet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, 270, 40));

        txtKetLunas.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        txtKetLunas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKetLunas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtKetLunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKetLunasActionPerformed(evt);
            }
        });
        Kasir.add(txtKetLunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, 220, 35));

        Isi.add(Kasir, "card4");

        Data.setBackground(new java.awt.Color(255, 255, 255));
        Data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextData.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        TextData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextData.setText("D A T A  P E L A N G G A N");
        Data.add(TextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 61, 325, -1));

        ImageData1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Data1.jpg"))); // NOI18N
        Data.add(ImageData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 380, -1, -1));

        ImageData2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Data3.jpg"))); // NOI18N
        Data.add(ImageData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, -1, -1));

        ImageData3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Data2.jpg"))); // NOI18N
        Data.add(ImageData3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, 630, -1));

        btnDataHapus.setBackground(new java.awt.Color(87, 138, 175));
        btnDataHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDataHapusMousePressed(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataHapusMouseExited(evt);
            }
        });
        btnDataHapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKembali1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKembali1.setForeground(new java.awt.Color(255, 255, 255));
        TextKembali1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKembali1.setText("H A P U S");
        btnDataHapus.add(TextKembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        Data.add(btnDataHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 330, 50));

        btnDataUbah.setBackground(new java.awt.Color(87, 138, 175));
        btnDataUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDataUbahMousePressed(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataUbahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataUbahMouseExited(evt);
            }
        });
        btnDataUbah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKembali5.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKembali5.setForeground(new java.awt.Color(255, 255, 255));
        TextKembali5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKembali5.setText("U B A H");
        btnDataUbah.add(TextKembali5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        Data.add(btnDataUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 330, 50));

        btnDataKembali1.setBackground(new java.awt.Color(87, 138, 175));
        btnDataKembali1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataKembali1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataKembali1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDataKembali1MousePressed(evt);
            }
        });
        btnDataKembali1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKembali3.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKembali3.setForeground(new java.awt.Color(255, 255, 255));
        TextKembali3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKembali3.setText("K E M B A L I  K E  K A S I R");
        btnDataKembali1.add(TextKembali3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 50));

        Data.add(btnDataKembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, -1, 50));

        btnDataKembali2.setBackground(new java.awt.Color(87, 138, 175));
        btnDataKembali2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataKembali2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataKembali2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDataKembali2MousePressed(evt);
            }
        });
        btnDataKembali2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKembali2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKembali2.setForeground(new java.awt.Color(255, 255, 255));
        TextKembali2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKembali2.setText("K E M B A L I  K E  B E R A N D A");
        btnDataKembali2.add(TextKembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 50));

        Data.add(btnDataKembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, 460, 50));

        btnDataKeluar.setBackground(new java.awt.Color(87, 138, 175));
        btnDataKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataKeluarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDataKeluarMousePressed(evt);
            }
        });
        btnDataKeluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextDataKeluar.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextDataKeluar.setForeground(new java.awt.Color(255, 255, 255));
        TextDataKeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextDataKeluar.setText("K E L U A R");
        btnDataKeluar.add(TextDataKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 50));

        Data.add(btnDataKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 750, 320, 50));

        tablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePelanggan);

        Data.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 810, 230));

        TextKembali4.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKembali4.setForeground(new java.awt.Color(255, 255, 255));
        TextKembali4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKembali4.setText("U B A H");
        Data.add(TextKembali4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 330, 50));

        Isi.add(Data, "card5");

        PanelUtama.add(Isi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1920, 1010));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        // TODO add your handling code here:
        btnMenu.setBackground(new Color(62,113,150));

        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();

        Isi.add(Menu);
        Isi.repaint();
        Isi.revalidate();

    }//GEN-LAST:event_btnMenuMousePressed

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        // TODO add your handling code here:
        btnMenu.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        // TODO add your handling code here:
        btnMenu.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnKasirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirMouseEntered
        // TODO add your handling code here:
        btnKasir.setBackground(new Color(215,215,215));
    }//GEN-LAST:event_btnKasirMouseEntered

    private void btnKasirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirMouseExited
        // TODO add your handling code here:
        btnKasir.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btnKasirMouseExited

    private void btnKasirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirMousePressed
        // TODO add your handling code here:
        btnKasir.setBackground(new Color(189,189,189));

        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();

        Isi.add(Kasir);
        Isi.repaint();
        Isi.revalidate();

    }//GEN-LAST:event_btnKasirMousePressed

    private void btnDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataMouseEntered
        // TODO add your handling code here:
        btnData.setBackground(new Color(215,215,215));
    }//GEN-LAST:event_btnDataMouseEntered

    private void btnDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataMouseExited
        // TODO add your handling code here:
        btnData.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btnDataMouseExited

    private void btnDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataMousePressed
        // TODO add your handling code here:
        btnData.setBackground(new Color(189,189,189));

        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();

        Isi.add(Data);
        Isi.repaint();
        Isi.revalidate();

    }//GEN-LAST:event_btnDataMousePressed

    private void txtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBeratActionPerformed

    private void txtTerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerimaActionPerformed

    private void txtSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelesaiActionPerformed

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    private void btnHitungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseEntered
        // TODO add your handling code here:
        btnHitung.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnHitungMouseEntered

    private void btnHitungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseExited
        // TODO add your handling code here:
        btnHitung.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnHitungMouseExited

    private void btnHitungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMousePressed
        // TODO add your handling code here:
        btnHitung.setBackground(new Color(62,113,150));
        Integer Berat,Jumlah;
        Integer HargaPerBerat = 5000;

        Berat = Integer.parseInt(txtBerat.getText());
        Jumlah = Berat * HargaPerBerat;
        txtTotal.setText(Integer.toString(Jumlah));
    }//GEN-LAST:event_btnHitungMousePressed

    private void btnSimpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseEntered
        // TODO add your handling code here:
        btnSimpan.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnSimpanMouseEntered

    private void btnSimpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseExited
        // TODO add your handling code here:
        btnSimpan.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnSimpanMouseExited

    private void btnSimpanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMousePressed
        // TODO add your handling code here:
        btnSimpan.setBackground(new Color(62,113,150));
        controller.insertPelanggan(this);
    }//GEN-LAST:event_btnSimpanMousePressed

    private void btnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseEntered
        // TODO add your handling code here:
        btnReset.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnResetMouseEntered

    private void btnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseExited
        // TODO add your handling code here:
        btnReset.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnResetMouseExited

    private void btnResetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMousePressed
        // TODO add your handling code here:
        btnReset.setBackground(new Color(62,113,150));
        controller.resetPelanggan(this);
    }//GEN-LAST:event_btnResetMousePressed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtKetSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKetSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKetSelesaiActionPerformed

    private void btnKasirKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirKeluarMouseEntered
        // TODO add your handling code here:
        btnKasirKeluar.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnKasirKeluarMouseEntered

    private void btnKasirKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirKeluarMouseExited
        // TODO add your handling code here:
        btnKasirKeluar.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnKasirKeluarMouseExited

    private void btnKasirKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirKeluarMousePressed
        // TODO add your handling code here:
        btnKasirKeluar.setBackground(new Color(62,113,150));
        System.exit(0);
    }//GEN-LAST:event_btnKasirKeluarMousePressed

    private void btnLihatDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLihatDataMouseEntered
        // TODO add your handling code here:
        btnLihatData.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnLihatDataMouseEntered

    private void btnLihatDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLihatDataMouseExited
        // TODO add your handling code here:
        btnLihatData.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnLihatDataMouseExited

    private void btnLihatDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLihatDataMousePressed
        // TODO add your handling code here:
        btnLihatData.setBackground(new Color(62,113,150));

        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();

        Isi.add(Data);
        Isi.repaint();
        Isi.revalidate();

    }//GEN-LAST:event_btnLihatDataMousePressed

    private void btnKasirKembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirKembaliMouseEntered
        // TODO add your handling code here:
        btnKasirKembali.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnKasirKembaliMouseEntered

    private void btnKasirKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirKembaliMouseExited
        // TODO add your handling code here:
        btnKasirKembali.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnKasirKembaliMouseExited

    private void btnKasirKembaliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirKembaliMousePressed
        // TODO add your handling code here:
        btnKasirKembali.setBackground(new Color(62,113,150));

        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();

        Isi.add(Beranda);
        Isi.repaint();
        Isi.revalidate();

    }//GEN-LAST:event_btnKasirKembaliMousePressed

    private void btnDataUbahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataUbahMouseEntered
        // TODO add your handling code here:
        btnDataUbah.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnDataUbahMouseEntered

    private void btnDataUbahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataUbahMouseExited
        // TODO add your handling code here:
        btnDataUbah.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnDataUbahMouseExited

    private void btnDataUbahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataUbahMousePressed
        // TODO add your handling code here:
        btnDataUbah.setBackground(new Color(62,113,150));
        controller.updatePelanggan(this);
    }//GEN-LAST:event_btnDataUbahMousePressed

    private void btnDataKembali1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKembali1MouseEntered
        // TODO add your handling code here:
        btnDataKembali1.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnDataKembali1MouseEntered

    private void btnDataKembali1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKembali1MouseExited
        // TODO add your handling code here:
        btnDataKembali1.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnDataKembali1MouseExited

    private void btnDataKembali1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKembali1MousePressed
        // TODO add your handling code here:
        btnDataKembali1.setBackground(new Color(62,113,150));
        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();

        Isi.add(Kasir);
        Isi.repaint();
        Isi.revalidate();
    }//GEN-LAST:event_btnDataKembali1MousePressed

    private void btnDataKembali2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKembali2MouseEntered
        // TODO add your handling code here:
        btnDataKembali2.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnDataKembali2MouseEntered

    private void btnDataKembali2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKembali2MouseExited
        // TODO add your handling code here:
        btnDataKembali2.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnDataKembali2MouseExited

    private void btnDataKembali2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKembali2MousePressed
        // TODO add your handling code here:
        btnDataKembali2.setBackground(new Color(62,113,150));

        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();

        Isi.add(Beranda);
        Isi.repaint();
        Isi.revalidate();

    }//GEN-LAST:event_btnDataKembali2MousePressed

    private void btnDataKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKeluarMouseEntered
        // TODO add your handling code here:
        btnDataKeluar.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnDataKeluarMouseEntered

    private void btnDataKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKeluarMouseExited
        // TODO add your handling code here:
        btnDataKeluar.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnDataKeluarMouseExited

    private void btnDataKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataKeluarMousePressed
        // TODO add your handling code here:
        btnDataKeluar.setBackground(new Color(62,113,150));
        System.exit(0);
    }//GEN-LAST:event_btnDataKeluarMousePressed

    private void txtTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyPressed

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeyReleased

    private void txtBeratKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeratKeyTyped
        // TODO add your handling code here:
        char ketikan = evt.getKeyChar();
        if (!(Character.isDigit(ketikan))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtBeratKeyTyped

    private void txtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyTyped
        // TODO add your handling code here:
        char ketikan = evt.getKeyChar();
        if (!(Character.isDigit(ketikan))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTotalKeyTyped

    private void txtBeratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBeratKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBeratKeyReleased

    private void btnDataHapusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataHapusMousePressed
        // TODO add your handling code here:
        btnDataHapus.setBackground(new Color(62,113,150));
        controller.deletePelanggan(this);
    }//GEN-LAST:event_btnDataHapusMousePressed

    private void btnDataHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataHapusMouseEntered
        // TODO add your handling code here:
        btnDataHapus.setBackground(new Color(113,164,201));
    }//GEN-LAST:event_btnDataHapusMouseEntered

    private void btnDataHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataHapusMouseExited
        // TODO add your handling code here:
        btnDataHapus.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnDataHapusMouseExited

    private void txtKetLunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKetLunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKetLunasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Beranda;
    private javax.swing.JPanel Data;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel IconHeader;
    private javax.swing.JLabel IconMenu;
    private javax.swing.JLabel ImageBeranda1;
    private javax.swing.JLabel ImageBeranda2;
    private javax.swing.JLabel ImageBeranda3;
    private javax.swing.JLabel ImageData1;
    private javax.swing.JLabel ImageData2;
    private javax.swing.JLabel ImageData3;
    private javax.swing.JLabel ImageKasir1;
    private javax.swing.JLabel ImageKasir2;
    private javax.swing.JLabel ImageKasir3;
    private javax.swing.JPanel Isi;
    private javax.swing.JPanel Kasir;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JLabel TextBeranda1;
    private javax.swing.JLabel TextBeranda2;
    private javax.swing.JLabel TextBeranda3;
    private javax.swing.JLabel TextBeranda4;
    private javax.swing.JLabel TextBeranda5;
    private javax.swing.JLabel TextBeranda6;
    private javax.swing.JLabel TextBeranda7;
    private javax.swing.JLabel TextData;
    private javax.swing.JLabel TextDataKeluar;
    private javax.swing.JLabel TextHeader;
    private javax.swing.JLabel TextKasir;
    private javax.swing.JLabel TextKasirBerat;
    private javax.swing.JLabel TextKasirKeluar;
    private javax.swing.JLabel TextKasirKembali;
    private javax.swing.JLabel TextKasirKet;
    private javax.swing.JLabel TextKasirKet1;
    private javax.swing.JLabel TextKasirKet2;
    private javax.swing.JLabel TextKasirNama;
    private javax.swing.JLabel TextKasirNo;
    private javax.swing.JLabel TextKasirReset;
    private javax.swing.JLabel TextKasirSelesai;
    private javax.swing.JLabel TextKasirSimpan;
    private javax.swing.JLabel TextKasirTelp;
    private javax.swing.JLabel TextKasirTerima;
    private javax.swing.JLabel TextKasirTotal;
    private javax.swing.JLabel TextKembali1;
    private javax.swing.JLabel TextKembali2;
    private javax.swing.JLabel TextKembali3;
    private javax.swing.JLabel TextKembali4;
    private javax.swing.JLabel TextKembali5;
    private javax.swing.JLabel TextLihatData;
    private javax.swing.JLabel TextMenu;
    private javax.swing.JLabel TextMenuData;
    private javax.swing.JLabel TextMenuKasir;
    private javax.swing.JPanel btnData;
    private javax.swing.JPanel btnDataHapus;
    private javax.swing.JPanel btnDataKeluar;
    private javax.swing.JPanel btnDataKembali1;
    private javax.swing.JPanel btnDataKembali2;
    private javax.swing.JPanel btnDataUbah;
    private javax.swing.JPanel btnHitung;
    private javax.swing.JPanel btnKasir;
    private javax.swing.JPanel btnKasirKeluar;
    private javax.swing.JPanel btnKasirKembali;
    private javax.swing.JPanel btnLihatData;
    private javax.swing.JPanel btnMenu;
    private javax.swing.JPanel btnReset;
    private javax.swing.JPanel btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePelanggan;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtKetLunas;
    private javax.swing.JTextField txtKetSelesai;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtSelesai;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTerima;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(PelangganModel model) {
            txtNo.setText(model.getNo_rak()+ "");
            txtNama.setText(model.getNama());
            txtBerat.setText(model.getBerat()+ "");
            txtTerima.setText(model.getTgl_terima());
            txtSelesai.setText(model.getTgl_selesai());
            txtTelp.setText(model.getTelp());
            txtTotal.setText(model.getTotal()+ "");
            txtKetLunas.setText(model.getKet_lunas());
            txtKetSelesai.setText(model.getKet_selesai());
    }

    @Override
    public void onInsert(Pelanggan pelanggan) {
        tableModel.add(pelanggan);
    }

    @Override
    public void onDelete() {
        int index = tablePelanggan.getSelectedRow();
        tableModel.remove(index);
    }

    @Override
    public void onUpdate(Pelanggan pelanggan) {
        int index = tablePelanggan.getSelectedRow();
        tableModel.set(index, pelanggan);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            Pelanggan model = tableModel.get(tablePelanggan.getSelectedRow());
            txtNo.setText(model.getNo_rak()+ "");
            txtNama.setText(model.getNama());
            txtBerat.setText(model.getBerat()+ "");
            txtTerima.setText(model.getTgl_terima());
            txtSelesai.setText(model.getKet_selesai());
            txtTelp.setText(model.getTelp());
            txtTotal.setText(model.getTotal()+ "");
            txtKetLunas.setText(model.getKet_lunas());
            txtKetSelesai.setText(model.getKet_selesai());
        } catch (IndexOutOfBoundsException exception) {
        }

    
    }
    
    public void loadDatabase() throws SQLException, PelangganException {
        PelangganDao dao = LaundryskuyDatabase.getPelangganDao();
        tableModel.setList(dao.selectAllPelanggan());    }
}
