/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.laundryskuy.view;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class HalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        TextHeader = new javax.swing.JLabel();
        IconHeader = new javax.swing.JLabel();
        btnMenu = new javax.swing.JPanel();
        IconMenu = new javax.swing.JLabel();
        Isi = new javax.swing.JPanel();
        Beranda = new javax.swing.JPanel();
        TextBeranda1 = new javax.swing.JLabel();
        TextBeranda2 = new javax.swing.JLabel();
        TextBeranda3 = new javax.swing.JLabel();
        TextBeranda4 = new javax.swing.JLabel();
        TextBeranda5 = new javax.swing.JLabel();
        TextBeranda6 = new javax.swing.JLabel();
        TextBeranda7 = new javax.swing.JLabel();
        ImageBeranda1 = new javax.swing.JLabel();
        ImageBeranda2 = new javax.swing.JLabel();
        ImageBeranda3 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnKasir = new javax.swing.JPanel();
        TextMenuKasir = new javax.swing.JLabel();
        btnData = new javax.swing.JPanel();
        TextMenuData = new javax.swing.JLabel();
        TextMenu = new javax.swing.JLabel();
        Kasir = new javax.swing.JPanel();
        TextKasir = new javax.swing.JLabel();
        TextKasirNama = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        TextKasirBerat = new javax.swing.JLabel();
        txtBerat = new javax.swing.JTextField();
        TextKasirTerima = new javax.swing.JLabel();
        txtTerima = new javax.swing.JTextField();
        TextKasirSelesai = new javax.swing.JLabel();
        txtSelesai = new javax.swing.JTextField();
        TextKasirTelp = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        btnHitung = new javax.swing.JPanel();
        TextKasirHitung = new javax.swing.JLabel();
        btnReset = new javax.swing.JPanel();
        TextKasirReset = new javax.swing.JLabel();
        TextKasirTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        ImageKasir1 = new javax.swing.JLabel();
        ImageKasir2 = new javax.swing.JLabel();
        ImageKasir3 = new javax.swing.JLabel();
        ImageKasir4 = new javax.swing.JLabel();
        ImageKasir5 = new javax.swing.JLabel();
        Data = new javax.swing.JPanel();
        TextData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));
        PanelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(87, 138, 175));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextHeader.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        TextHeader.setText("LAUNDRYSKUY");
        Header.add(TextHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        IconHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Icon/Logo.png"))); // NOI18N
        Header.add(IconHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, 50));

        btnMenu.setBackground(new java.awt.Color(87, 138, 175));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });
        btnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Icon/Menu.png"))); // NOI18N
        btnMenu.add(IconMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        Header.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1840, 20, 50, 30));

        PanelUtama.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 70));

        Isi.setBackground(new java.awt.Color(255, 255, 255));
        Isi.setLayout(new java.awt.CardLayout());

        Beranda.setBackground(new java.awt.Color(255, 255, 255));
        Beranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextBeranda1.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        TextBeranda1.setText("S E L A M A T  D A T A N G");
        Beranda.add(TextBeranda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 30));

        TextBeranda2.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextBeranda2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextBeranda2.setText("Semoga anda puas dengan pelayanan kami :)");
        Beranda.add(TextBeranda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 490, 40));

        TextBeranda3.setFont(new java.awt.Font("Leelawadee", 2, 24)); // NOI18N
        TextBeranda3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBeranda3.setText("LaundrySkuy");
        Beranda.add(TextBeranda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 150, 30));

        TextBeranda4.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextBeranda4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBeranda4.setText("Adalah laundry dengan pelayanan yang santuy,");
        Beranda.add(TextBeranda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 590, 30));

        TextBeranda5.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextBeranda5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextBeranda5.setText("cepat, rapih, dan nyaman. Dengan menggunakan mesin cuci terbaik");
        Beranda.add(TextBeranda5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 730, 40));

        TextBeranda6.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextBeranda6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextBeranda6.setText("yang ada di negeri ini, kami juga menggunakan sabun dan pewangi ");
        Beranda.add(TextBeranda6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 760, 40));

        TextBeranda7.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextBeranda7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TextBeranda7.setText("setara parfum dunia dengan bau yang tahan lama. ");
        Beranda.add(TextBeranda7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 760, 40));

        ImageBeranda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Beranda3.jpg"))); // NOI18N
        Beranda.add(ImageBeranda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, 450, -1));

        ImageBeranda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Beranda1.jpg"))); // NOI18N
        Beranda.add(ImageBeranda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 80, -1, -1));

        ImageBeranda3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Beranda2.jpg"))); // NOI18N
        Beranda.add(ImageBeranda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        Isi.add(Beranda, "card2");

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKasirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKasirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKasirMousePressed(evt);
            }
        });

        TextMenuKasir.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextMenuKasir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextMenuKasir.setText("K A S I R");

        javax.swing.GroupLayout btnKasirLayout = new javax.swing.GroupLayout(btnKasir);
        btnKasir.setLayout(btnKasirLayout);
        btnKasirLayout.setHorizontalGroup(
            btnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextMenuKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        btnKasirLayout.setVerticalGroup(
            btnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextMenuKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );

        Menu.add(btnKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        btnData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDataMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDataMousePressed(evt);
            }
        });

        TextMenuData.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextMenuData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextMenuData.setText("D A T A  P E L A N G G A N");

        javax.swing.GroupLayout btnDataLayout = new javax.swing.GroupLayout(btnData);
        btnData.setLayout(btnDataLayout);
        btnDataLayout.setHorizontalGroup(
            btnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextMenuData, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        btnDataLayout.setVerticalGroup(
            btnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextMenuData, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );

        Menu.add(btnData, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 360, -1));

        TextMenu.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        TextMenu.setText("M E N U");
        Menu.add(TextMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, -1));

        Isi.add(Menu, "card3");

        Kasir.setBackground(new java.awt.Color(255, 255, 255));
        Kasir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKasir.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        TextKasir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasir.setText("K A S I R");
        Kasir.add(TextKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 61, 298, -1));

        TextKasirNama.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirNama.setText("N A M A  P E L A N G G A N");
        Kasir.add(TextKasirNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 338, 35));

        txtNama.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        Kasir.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 280, 35));

        TextKasirBerat.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirBerat.setText("B E R A T  P A K A I A N");
        Kasir.add(TextKasirBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 323, 30));

        txtBerat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBeratActionPerformed(evt);
            }
        });
        Kasir.add(txtBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 280, 35));

        TextKasirTerima.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirTerima.setText("T A N G G A L   T E R I M A");
        Kasir.add(TextKasirTerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 323, 35));

        txtTerima.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerimaActionPerformed(evt);
            }
        });
        Kasir.add(txtTerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 280, 35));

        TextKasirSelesai.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirSelesai.setText("T A N G G A L   S E L E S A I ");
        Kasir.add(TextKasirSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 338, 35));

        txtSelesai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSelesaiActionPerformed(evt);
            }
        });
        Kasir.add(txtSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 280, 35));

        TextKasirTelp.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirTelp.setText("N O  T E L E P O N");
        Kasir.add(TextKasirTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 323, 40));

        txtTelp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });
        Kasir.add(txtTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 280, 35));

        btnHitung.setBackground(new java.awt.Color(87, 138, 175));
        btnHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHitungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHitungMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHitungMousePressed(evt);
            }
        });
        btnHitung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKasirHitung.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKasirHitung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasirHitung.setText("H I T U N G");
        btnHitung.add(TextKasirHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        Kasir.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 482, -1, -1));

        btnReset.setBackground(new java.awt.Color(87, 138, 175));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnResetMousePressed(evt);
            }
        });
        btnReset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextKasirReset.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        TextKasirReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextKasirReset.setText("R E S E T");
        btnReset.add(TextKasirReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        Kasir.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 549, -1, -1));

        TextKasirTotal.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        TextKasirTotal.setText("T O T A L  P E M B A Y A R A N");
        Kasir.add(TextKasirTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 338, -1));

        txtTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        Kasir.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, 280, 35));

        ImageKasir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Kasir4.jpg"))); // NOI18N
        Kasir.add(ImageKasir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 430, -1, -1));

        ImageKasir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Kasir3.jpg"))); // NOI18N
        Kasir.add(ImageKasir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 90, 350, -1));

        ImageKasir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Kasir5.jpg"))); // NOI18N
        Kasir.add(ImageKasir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 50, -1, -1));

        ImageKasir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Kasir2.jpg"))); // NOI18N
        Kasir.add(ImageKasir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, -1, -1));

        ImageKasir5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Kasir1.jpg"))); // NOI18N
        Kasir.add(ImageKasir5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 50, -1, -1));

        Isi.add(Kasir, "card4");

        Data.setBackground(new java.awt.Color(255, 255, 255));
        Data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextData.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        TextData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextData.setText("D A T A  P E L A N G G A N");
        Data.add(TextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 61, 325, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Data1.jpg"))); // NOI18N
        Data.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 380, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Data3.jpg"))); // NOI18N
        Data.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Data2.jpg"))); // NOI18N
        Data.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, 630, -1));

        Isi.add(Data, "card5");

        PanelUtama.add(Isi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1920, 1010));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        // TODO add your handling code here:
        btnMenu.setBackground(new Color(113,164,201)); 
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        // TODO add your handling code here:
        btnMenu.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        // TODO add your handling code here:
        btnMenu.setBackground(new Color(62,113,150));
        
        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();
        
        Isi.add(Menu);
        Isi.repaint();
        Isi.revalidate();
        
    }//GEN-LAST:event_btnMenuMousePressed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtTerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerimaActionPerformed

    private void txtBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBeratActionPerformed

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    private void btnHitungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseEntered
        // TODO add your handling code here:
        btnHitung.setBackground(new Color(113,164,201)); 
    }//GEN-LAST:event_btnHitungMouseEntered

    private void btnHitungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMouseExited
        // TODO add your handling code here:
        btnHitung.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnHitungMouseExited

    private void btnHitungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMousePressed
        // TODO add your handling code here:
        btnHitung.setBackground(new Color(62,113,150));
    }//GEN-LAST:event_btnHitungMousePressed

    private void btnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseEntered
        // TODO add your handling code here:
        btnReset.setBackground(new Color(113,164,201)); 
    }//GEN-LAST:event_btnResetMouseEntered

    private void btnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseExited
        // TODO add your handling code here:
        btnReset.setBackground(new Color(87,138,175));
    }//GEN-LAST:event_btnResetMouseExited

    private void btnResetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMousePressed
        // TODO add your handling code here:
        btnReset.setBackground(new Color(62,113,150));
    }//GEN-LAST:event_btnResetMousePressed

    private void btnKasirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirMouseEntered
        // TODO add your handling code here:
         btnKasir.setBackground(new Color(215,215,215));
    }//GEN-LAST:event_btnKasirMouseEntered

    private void btnKasirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirMouseExited
        // TODO add your handling code here:
         btnKasir.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btnKasirMouseExited

    private void btnKasirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKasirMousePressed
        // TODO add your handling code here:
        btnKasir.setBackground(new Color(189,189,189));
        
        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();
        
        Isi.add(Kasir);
        Isi.repaint();
        Isi.revalidate();
        
    }//GEN-LAST:event_btnKasirMousePressed

    private void btnDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataMouseEntered
        // TODO add your handling code here:
        btnData.setBackground(new Color(215,215,215));
    }//GEN-LAST:event_btnDataMouseEntered

    private void btnDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataMouseExited
        // TODO add your handling code here:
        btnData.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_btnDataMouseExited

    private void btnDataMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataMousePressed
        // TODO add your handling code here:
        btnData.setBackground(new Color(189,189,189));
        
        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();
        
        Isi.add(Data);
        Isi.repaint();
        Isi.revalidate();
        
    }//GEN-LAST:event_btnDataMousePressed

    private void txtSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSelesaiActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Beranda;
    private javax.swing.JPanel Data;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel IconHeader;
    private javax.swing.JLabel IconMenu;
    private javax.swing.JLabel ImageBeranda1;
    private javax.swing.JLabel ImageBeranda2;
    private javax.swing.JLabel ImageBeranda3;
    private javax.swing.JLabel ImageKasir1;
    private javax.swing.JLabel ImageKasir2;
    private javax.swing.JLabel ImageKasir3;
    private javax.swing.JLabel ImageKasir4;
    private javax.swing.JLabel ImageKasir5;
    private javax.swing.JPanel Isi;
    private javax.swing.JPanel Kasir;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JLabel TextBeranda1;
    private javax.swing.JLabel TextBeranda2;
    private javax.swing.JLabel TextBeranda3;
    private javax.swing.JLabel TextBeranda4;
    private javax.swing.JLabel TextBeranda5;
    private javax.swing.JLabel TextBeranda6;
    private javax.swing.JLabel TextBeranda7;
    private javax.swing.JLabel TextData;
    private javax.swing.JLabel TextHeader;
    private javax.swing.JLabel TextKasir;
    private javax.swing.JLabel TextKasirBerat;
    private javax.swing.JLabel TextKasirHitung;
    private javax.swing.JLabel TextKasirNama;
    private javax.swing.JLabel TextKasirReset;
    private javax.swing.JLabel TextKasirSelesai;
    private javax.swing.JLabel TextKasirTelp;
    private javax.swing.JLabel TextKasirTerima;
    private javax.swing.JLabel TextKasirTotal;
    private javax.swing.JLabel TextMenu;
    private javax.swing.JLabel TextMenuData;
    private javax.swing.JLabel TextMenuKasir;
    private javax.swing.JPanel btnData;
    private javax.swing.JPanel btnHitung;
    private javax.swing.JPanel btnKasir;
    private javax.swing.JPanel btnMenu;
    private javax.swing.JPanel btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtBerat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSelesai;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTerima;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
