/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.laundryskuy.view;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class HalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Isi = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnKasir = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnData = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));
        PanelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(200, 162, 122));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel2.setText("LAUNDRYSKUY");
        Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Icon/Logo.png"))); // NOI18N
        Header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, 50));

        btnMenu.setBackground(new java.awt.Color(200, 162, 122));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });
        btnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Icon/Menu.png"))); // NOI18N
        btnMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        Header.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 20, 50, 30));

        PanelUtama.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 70));

        Isi.setBackground(new java.awt.Color(255, 255, 255));
        Isi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Background.jpg"))); // NOI18N
        Isi.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 900, 490));

        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        jLabel10.setText("S E L A M A T  D A T A N G");
        Isi.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, 30));

        jLabel14.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Isi.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 810, 520, 30));

        jLabel15.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Semoga anda puas dengan pelayanan kami :)");
        Isi.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 490, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Background2.jpg"))); // NOI18N
        Isi.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 390, 500));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Background.jpg"))); // NOI18N
        Isi.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 450, 730, 490));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Background.jpg"))); // NOI18N
        Isi.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 730, 490));

        jLabel17.setFont(new java.awt.Font("Leelawadee", 2, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("LaundrySkuy");
        Isi.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 150, 30));

        jLabel18.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Adalah laundry dengan pelayanan yang santuy,");
        Isi.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 590, 30));

        jLabel19.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("cepat, rapih, dan nyaman. Dengan menggunakan mesin cuci terbaik");
        Isi.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 730, 40));

        jLabel20.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("yang ada di negeri ini, kami juga menggunakan sabun dan pewangi ");
        Isi.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 760, 40));

        jLabel21.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("setara parfum dunia dengan bau yang tahan lama. ");
        Isi.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 760, 40));

        PanelUtama.add(Isi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1920, 1010));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel5.setText("K A S I R");

        javax.swing.GroupLayout btnKasirLayout = new javax.swing.GroupLayout(btnKasir);
        btnKasir.setLayout(btnKasirLayout);
        btnKasirLayout.setHorizontalGroup(
            btnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKasirLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel5)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        btnKasirLayout.setVerticalGroup(
            btnKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKasirLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        Menu.add(btnKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee", 0, 24)); // NOI18N
        jLabel6.setText("D A T A  P E L A N G G A N");

        javax.swing.GroupLayout btnDataLayout = new javax.swing.GroupLayout(btnData);
        btnData.setLayout(btnDataLayout);
        btnDataLayout.setHorizontalGroup(
            btnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDataLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(34, 34, 34))
        );
        btnDataLayout.setVerticalGroup(
            btnDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDataLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel6)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        Menu.add(btnData, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        jLabel3.setText("M E N U");
        Menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Menu.jpg"))); // NOI18N
        Menu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 80, -1, 700));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laundryskuy/Images/Menu.jpg"))); // NOI18N
        Menu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 88, -1, 674));

        PanelUtama.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1010));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        // TODO add your handling code here:
        btnMenu.setBackground(new Color(187,149,109)); 
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        // TODO add your handling code here:
        btnMenu.setBackground(new Color(200,162,122));
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        // TODO add your handling code here:
        btnMenu.setBackground(new Color(175,137,97));
        
        Isi.removeAll();
        Isi.repaint();
        Isi.revalidate();
        
        Isi.add(Menu);
        Isi.repaint();
        Isi.revalidate();
        
    }//GEN-LAST:event_btnMenuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Isi;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JPanel btnData;
    private javax.swing.JPanel btnKasir;
    private javax.swing.JPanel btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
